/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import { GlobalComponents } from 'vue'

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next')['BAlert']
    BButton: typeof import('bootstrap-vue-next')['BButton']
    BCard: typeof import('bootstrap-vue-next')['BCard']
    BCardText: typeof import('bootstrap-vue-next')['BCardText']
    BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
    BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
    BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
    BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next')['BInputGroupText']
    BModal: typeof import('bootstrap-vue-next')['BModal']
    BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
    BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
    BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
    BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
    BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
    BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
    BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
    BTable: typeof import('bootstrap-vue-next')['BTable']
  }
  export interface GlobalDirectives {
    vBTooltip: typeof import('bootstrap-vue-next')['vBTooltip']
  }
}

// For TSX support
declare global {
  const BAlert: typeof import('bootstrap-vue-next')['BAlert']
  const BButton: typeof import('bootstrap-vue-next')['BButton']
  const BCard: typeof import('bootstrap-vue-next')['BCard']
  const BCardText: typeof import('bootstrap-vue-next')['BCardText']
  const BCollapse: typeof import('bootstrap-vue-next')['BCollapse']
  const BFormCheckbox: typeof import('bootstrap-vue-next')['BFormCheckbox']
  const BFormInput: typeof import('bootstrap-vue-next')['BFormInput']
  const BInputGroup: typeof import('bootstrap-vue-next')['BInputGroup']
  const BInputGroupText: typeof import('bootstrap-vue-next')['BInputGroupText']
  const BModal: typeof import('bootstrap-vue-next')['BModal']
  const BNavbar: typeof import('bootstrap-vue-next')['BNavbar']
  const BNavbarBrand: typeof import('bootstrap-vue-next')['BNavbarBrand']
  const BNavbarNav: typeof import('bootstrap-vue-next')['BNavbarNav']
  const BNavbarToggle: typeof import('bootstrap-vue-next')['BNavbarToggle']
  const BNavItem: typeof import('bootstrap-vue-next')['BNavItem']
  const BOffcanvas: typeof import('bootstrap-vue-next')['BOffcanvas']
  const BSpinner: typeof import('bootstrap-vue-next')['BSpinner']
  const BTable: typeof import('bootstrap-vue-next')['BTable']
}