name: CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
   build:
    runs-on: ubuntu-latest
    steps:  
      - name: Login
        uses: docker/login-action@v1.6.0
        with:
          username: ${{ secrets.DOCKER_LOGIN }}
          password: ${{ secrets.DOCKER_PASS }}
      - uses: actions/checkout@v2
      - name: docker build
        run: |
          docker build -t eabrega/astronav-web:$GITHUB_RUN_NUMBER .
          docker push eabrega/astronav-web:$GITHUB_RUN_NUMBER
          git tag b$GITHUB_RUN_NUMBER
          git push origin --tags
      - name: SSH Remote Commands
        uses: appleboy/ssh-action@v0.1.4
        env:
          TAG: ${GITHUB_RUN_NUMBER}
          LAG: "LAG" 
          MAG: $GITHUB_RUN_NUMBER
        with:
          envs: TAG,LAG,MAG
          host: ${{ secrets.DEPLOY_SERVER_IP }}
          port: ${{ secrets.DEPLOY_SERVER_PORT }}
          username: ${{ secrets.USER_NAME }}
          key: ${{ secrets.KEY }}
          script: |
            echo "$TAG $LAG $MAG"
            echo $TAG
            echo $MAG
            echo $LAG
            docker run -id -p 7010:80 --name astronav-web-1 eabrega/astronav-web:$TAG
